const SAVE_COUNTRIES = "SAVE_COUNTRIES";
const FILTER_CONTINENT = "FILTER_CONTINENT";
const SAVE_ACTIVITIES = "SAVE_ACTIVITIES";
const FILTER_ACTIVITIES = "FILTER_ACTIVITIES";
const A_Z_COUNTRIES = "A-Z_COUNTRIES";
const SET_PAGES = "SET_PAGES";
const SEARCH_COUNTRY = "SEARCH_COUNTRY";
const GET_NAMES = "GET_NAMES";

export { 
    SAVE_COUNTRIES,
    FILTER_CONTINENT,
    SAVE_ACTIVITIES,
    FILTER_ACTIVITIES,
    A_Z_COUNTRIES,
    SET_PAGES,
    SEARCH_COUNTRY,
    GET_NAMES
}